# Generated by Django 4.1 on 2022-08-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="slag",
            new_name="slug",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="slag",
            new_name="slug",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="slag",
            new_name="slug",
        ),
    ]
